version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - net
    volumes:
      - "db:/data/db"

networks:
  net:

volumes:
  shared:
    driver: local
  db:
    driver: local